CREATE TABLE [bkp].[AV_ts_customer_payment]
(
[audit_datetime] [datetime] NULL,
[customerpayment_record_state] [int] NOT NULL,
[customerpayment_audit_id] [uniqueidentifier] NOT NULL,
[customerpayment_cardholder_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_create_audit_id] [uniqueidentifier] NULL,
[customerpayment_customer_id] [uniqueidentifier] NULL,
[customerpayment_expiration_date] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_id] [uniqueidentifier] NOT NULL,
[customerpayment_issue_number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_paymentmethod_id] [uniqueidentifier] NULL,
[customerpayment_start_date] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_version] [int] NOT NULL,
[customerpayment_token] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_masked_account_number] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_account_number_hash] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_account_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_bank_name] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_bank_address] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_description] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_sort_code] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_due_date] [datetime] NULL,
[customerpayment_recurrence_start_date] [datetime] NULL,
[customerpayment_recurrence_end_date] [datetime] NULL,
[customerpayment_payment_frequency] [int] NULL,
[customerpayment_account_status] [int] NULL,
[customerpayment_account_holder] [int] NULL,
[customerpayment_bacs_reference_number] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_gift_certificate_number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_gift_certificate_redemption_number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_rejection_reason] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerpayment_created_on] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
