CREATE TABLE [bkp].[AV_ts_order_charge]
(
[audit_datetime] [datetime] NULL,
[ordercharge_record_state] [int] NOT NULL,
[ordercharge_add_charge2] [bigint] NULL,
[ordercharge_add_charge2_delta] [bigint] NULL,
[ordercharge_add_charge2_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge2_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge2_paid] [bigint] NULL,
[ordercharge_add_charge2_paid_delta] [bigint] NULL,
[ordercharge_add_charge2_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge2_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_amount] [bigint] NULL,
[ordercharge_amount_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge2] [bigint] NULL,
[ordercharge_incl_charge2_delta] [bigint] NULL,
[ordercharge_incl_charge2_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge2_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge2_paid] [bigint] NULL,
[ordercharge_incl_charge2_paid_delta] [bigint] NULL,
[ordercharge_incl_charge2_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge2_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_net] [bigint] NULL,
[ordercharge_net_delta] [bigint] NULL,
[ordercharge_net_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_net_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_net_paid] [bigint] NULL,
[ordercharge_net_paid_delta] [bigint] NULL,
[ordercharge_net_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_net_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_total] [bigint] NULL,
[ordercharge_total_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_audit_id] [uniqueidentifier] NOT NULL,
[ordercharge_comment] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_create_audit_id] [uniqueidentifier] NULL,
[ordercharge_id] [uniqueidentifier] NOT NULL,
[ordercharge_override_ticket_number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_item_id] [uniqueidentifier] NULL,
[ordercharge_performance_id] [uniqueidentifier] NULL,
[ordercharge_record_number] [int] NULL,
[ordercharge_print_status] [int] NOT NULL,
[ordercharge_print_count] [int] NULL,
[ordercharge_order_id] [uniqueidentifier] NOT NULL,
[ordercharge_rate_id] [uniqueidentifier] NULL,
[ordercharge_type] [tinyint] NOT NULL,
[ordercharge_version] [int] NOT NULL,
[ordercharge_service_charge_id] [uniqueidentifier] NULL,
[ordercharge_data1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_data2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_data3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_option_id] [uniqueidentifier] NULL,
[ordercharge_customer_offer_id] [uniqueidentifier] NULL,
[ordercharge_customer_id] [uniqueidentifier] NULL,
[ordercharge_ticket_id] [uniqueidentifier] NULL,
[ordercharge_incl_charge1] [bigint] NULL,
[ordercharge_incl_charge1_delta] [bigint] NULL,
[ordercharge_incl_charge1_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge1_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge1_paid] [bigint] NULL,
[ordercharge_incl_charge1_paid_delta] [bigint] NULL,
[ordercharge_incl_charge1_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge1_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge1] [bigint] NULL,
[ordercharge_add_charge1_delta] [bigint] NULL,
[ordercharge_add_charge1_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge1_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge1_paid] [bigint] NULL,
[ordercharge_add_charge1_paid_delta] [bigint] NULL,
[ordercharge_add_charge1_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge1_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge3] [bigint] NULL,
[ordercharge_incl_charge3_delta] [bigint] NULL,
[ordercharge_incl_charge3_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge3_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge3_paid] [bigint] NULL,
[ordercharge_incl_charge3_paid_delta] [bigint] NULL,
[ordercharge_incl_charge3_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge3_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge3] [bigint] NULL,
[ordercharge_add_charge3_delta] [bigint] NULL,
[ordercharge_add_charge3_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge3_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge3_paid] [bigint] NULL,
[ordercharge_add_charge3_paid_delta] [bigint] NULL,
[ordercharge_add_charge3_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge3_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge4] [bigint] NULL,
[ordercharge_incl_charge4_delta] [bigint] NULL,
[ordercharge_incl_charge4_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge4_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge4_paid] [bigint] NULL,
[ordercharge_incl_charge4_paid_delta] [bigint] NULL,
[ordercharge_incl_charge4_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge4_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge4] [bigint] NULL,
[ordercharge_add_charge4_delta] [bigint] NULL,
[ordercharge_add_charge4_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge4_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge4_paid] [bigint] NULL,
[ordercharge_add_charge4_paid_delta] [bigint] NULL,
[ordercharge_add_charge4_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge4_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge5] [bigint] NULL,
[ordercharge_incl_charge5_delta] [bigint] NULL,
[ordercharge_incl_charge5_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge5_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge5_paid] [bigint] NULL,
[ordercharge_incl_charge5_paid_delta] [bigint] NULL,
[ordercharge_incl_charge5_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_incl_charge5_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge5] [bigint] NULL,
[ordercharge_add_charge5_delta] [bigint] NULL,
[ordercharge_add_charge5_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge5_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge5_paid] [bigint] NULL,
[ordercharge_add_charge5_paid_delta] [bigint] NULL,
[ordercharge_add_charge5_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_add_charge5_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordercharge_processing_type] [int] NULL,
[ordercharge_owner_id] [uniqueidentifier] NULL,
[ordercharge_bundle_id] [uniqueidentifier] NULL,
[ordercharge_misc_item_id] [uniqueidentifier] NULL,
[ordercharge_transaction_state] [int] NOT NULL,
[ordercharge_agent_id] [uniqueidentifier] NULL,
[ordercharge_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
