CREATE TABLE [bkp].[AV_ts_order_marketing_data]
(
[ordermarketingdata_record_state] [int] NULL,
[ordermarketingdata_id] [uniqueidentifier] NULL,
[ordermarketingdata_order_id] [uniqueidentifier] NULL,
[ordermarketingdata_data1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data6] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data7] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data8] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data9] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data10] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data11] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data12] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data13] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data14] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data15] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data16] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data17] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data18] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data19] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data20] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data21] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data22] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data23] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data24] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data25] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data26] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data27] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data28] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data29] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data30] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data31] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data32] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data33] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data34] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data35] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data36] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data37] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data38] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data39] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data40] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data41] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data42] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data43] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data44] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data45] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data46] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data47] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data48] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data49] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_data50] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_date1] [datetime] NULL,
[ordermarketingdata_date2] [datetime] NULL,
[ordermarketingdata_date3] [datetime] NULL,
[ordermarketingdata_date4] [datetime] NULL,
[ordermarketingdata_date5] [datetime] NULL,
[ordermarketingdata_date6] [datetime] NULL,
[ordermarketingdata_date7] [datetime] NULL,
[ordermarketingdata_date8] [datetime] NULL,
[ordermarketingdata_date9] [datetime] NULL,
[ordermarketingdata_date10] [datetime] NULL,
[ordermarketingdata_currency1] [bigint] NULL,
[ordermarketingdata_currency1_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_currency2] [bigint] NULL,
[ordermarketingdata_currency2_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_currency3] [bigint] NULL,
[ordermarketingdata_currency3_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_currency4] [bigint] NULL,
[ordermarketingdata_currency4_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_currency5] [bigint] NULL,
[ordermarketingdata_currency5_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_currency6] [bigint] NULL,
[ordermarketingdata_currency6_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_currency7] [bigint] NULL,
[ordermarketingdata_currency7_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_currency8] [bigint] NULL,
[ordermarketingdata_currency8_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_currency9] [bigint] NULL,
[ordermarketingdata_currency9_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_currency10] [bigint] NULL,
[ordermarketingdata_currency10_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordermarketingdata_fixed1] [bigint] NULL,
[ordermarketingdata_fixed2] [bigint] NULL,
[ordermarketingdata_fixed3] [bigint] NULL,
[ordermarketingdata_fixed4] [bigint] NULL,
[ordermarketingdata_fixed5] [bigint] NULL,
[ordermarketingdata_fixed6] [bigint] NULL,
[ordermarketingdata_fixed7] [bigint] NULL,
[ordermarketingdata_fixed8] [bigint] NULL,
[ordermarketingdata_fixed9] [bigint] NULL,
[ordermarketingdata_fixed10] [bigint] NULL,
[ordermarketingdata_audit_id] [uniqueidentifier] NULL,
[ordermarketingdata_create_audit_id] [uniqueidentifier] NULL,
[ordermarketingdata_version] [int] NULL,
[ordermarketingdata_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
