CREATE TABLE [bkp].[AV_ts_performance]
(
[audit_datetime] [datetime] NULL,
[performance_record_state] [int] NOT NULL,
[performance_audit_id] [uniqueidentifier] NOT NULL,
[performance_alternative_overview_image] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_alternative_overview_x_size] [int] NULL,
[performance_alternative_overview_y_size] [int] NULL,
[performance_alternative_detailed_image] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_alternative_detailed_x_size] [int] NULL,
[performance_alternative_detailed_y_size] [int] NULL,
[performance_chart_id] [uniqueidentifier] NULL,
[performance_create_audit_id] [uniqueidentifier] NULL,
[performance_options] [int] NULL,
[performance_description] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_end_date] [datetime] NULL,
[performance_entry_date] [datetime] NULL,
[performance_fill_template_id] [uniqueidentifier] NULL,
[performance_group] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_hold_template_id] [uniqueidentifier] NULL,
[performance_id] [uniqueidentifier] NOT NULL,
[performance_merchant_description] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[performance_popupmessage] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_price_template_id] [uniqueidentifier] NULL,
[performance_rank] [int] NULL,
[performance_series_id] [uniqueidentifier] NULL,
[performance_series_performance_type_id] [uniqueidentifier] NULL,
[performance_short_description] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_start_date] [datetime] NULL,
[performance_ticket_template_id] [uniqueidentifier] NULL,
[performance_additional_info] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_logo1] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_logo2] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_version] [int] NOT NULL,
[performance_total_seats] [int] NULL,
[performance_producer_id] [uniqueidentifier] NULL,
[performance_gl_code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_gl_description1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_gl_description2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_caps_customer_group] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_external_reference_code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[performance_addon_article] [uniqueidentifier] NULL,
[performance_sales_type] [int] NULL,
[performance_upsell_article] [uniqueidentifier] NULL,
[performance_delivery_method_gateway] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
