CREATE TABLE [bkp].[AV_ts_venue]
(
[audit_datetime] [datetime] NULL,
[venue_record_state] [int] NOT NULL,
[venue_audit_id] [uniqueidentifier] NOT NULL,
[venue_overview_image] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_overview_x_size] [int] NULL,
[venue_overview_y_size] [int] NULL,
[venue_data9] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_data10] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_data11] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_data12] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_create_audit_id] [uniqueidentifier] NULL,
[venue_description] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_hold_template_id] [uniqueidentifier] NULL,
[venue_id] [uniqueidentifier] NOT NULL,
[venue_detailed_image] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[venue_group] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_percent_excellent] [int] NULL,
[venue_percent_good] [int] NULL,
[venue_percent_low] [int] NULL,
[venue_percent_sold_out] [int] NULL,
[venue_price_template_id] [uniqueidentifier] NULL,
[venue_quality_template_id] [uniqueidentifier] NULL,
[venue_screen_count] [int] NULL,
[venue_seat_template_id] [uniqueidentifier] NULL,
[venue_version] [int] NOT NULL,
[venue_detailed_x_size] [int] NULL,
[venue_detailed_y_size] [int] NULL,
[venue_best_section_option] [int] NULL,
[venue_display_options] [int] NULL,
[venue_data1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_data2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_data3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_data4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_data5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_data6] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_data7] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_data8] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_delivery_method_gateway] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
