CREATE TABLE [bkp].[AV_ts_service_charge]
(
[audit_datetime] [datetime] NULL,
[servicecharge_record_state] [int] NOT NULL,
[servicecharge_audit_id] [uniqueidentifier] NULL,
[servicecharge_create_audit_id] [uniqueidentifier] NULL,
[servicecharge_description] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_short_description] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_id] [uniqueidentifier] NOT NULL,
[servicecharge_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[servicecharge_ticket_template_id] [uniqueidentifier] NULL,
[servicecharge_type] [tinyint] NOT NULL,
[servicecharge_data1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_data2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_data3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_data4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_data5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_data6] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_data7] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_data8] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_date1] [datetime] NULL,
[servicecharge_date2] [datetime] NULL,
[servicecharge_fixed1] [bigint] NULL,
[servicecharge_fixed2] [bigint] NULL,
[servicecharge_currency1] [bigint] NULL,
[servicecharge_currency2] [bigint] NULL,
[servicecharge_version] [int] NULL,
[servicecharge_gl_code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_gl_description1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_gl_description2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_additional_info] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[servicecharge_policy] [int] NULL,
[servicecharge_addon_article_id] [uniqueidentifier] NULL,
[servicecharge_terms_conditions] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
