CREATE TABLE [bkp].[AV_ts_miscellaneous_item]
(
[audit_datetime] [datetime] NULL,
[miscellaneousitem_record_state] [int] NOT NULL,
[miscellaneousitem_audit_id] [uniqueidentifier] NULL,
[miscellaneousitem_create_audit_id] [uniqueidentifier] NULL,
[miscellaneousitem_description] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_short_description] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_search_image] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_id] [uniqueidentifier] NOT NULL,
[miscellaneousitem_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[miscellaneousitem_rank] [int] NULL,
[miscellaneousitem_ticket_template_id] [uniqueidentifier] NULL,
[miscellaneousitem_type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_data1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_data2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_data3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_data4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_data5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_data6] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_data7] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_data8] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_date1] [datetime] NULL,
[miscellaneousitem_date2] [datetime] NULL,
[miscellaneousitem_fixed1] [bigint] NULL,
[miscellaneousitem_fixed2] [bigint] NULL,
[miscellaneousitem_currency1] [bigint] NULL,
[miscellaneousitem_currency2] [bigint] NULL,
[miscellaneousitem_version] [int] NULL,
[miscellaneousitem_producer_id] [uniqueidentifier] NULL,
[miscellaneousitem_gl_code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_gl_description1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_gl_description2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_detailed_description] [uniqueidentifier] NULL,
[miscellaneousitem_addon_article] [uniqueidentifier] NULL,
[miscellaneousitem_search_image2] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_additional_info] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[miscellaneousitem_start_date] [datetime] NULL,
[miscellaneousitem_end_date] [datetime] NULL,
[miscellaneousitem_sales_type] [int] NULL,
[miscellaneousitem_upsell_article] [uniqueidentifier] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
