CREATE TABLE [bkp].[AV_ts_gift_certificate]
(
[audit_datetime] [datetime] NULL,
[gift_certificate_record_state] [int] NOT NULL,
[gift_certificate_amount] [bigint] NULL,
[gift_certificate_amount_delta] [bigint] NULL,
[gift_certificate_net_paid] [bigint] NULL,
[gift_certificate_net_paid_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_net_paid_delta] [bigint] NULL,
[gift_certificate_net_paid_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_audit_id] [uniqueidentifier] NOT NULL,
[gift_certificate_auth_amount] [bigint] NULL,
[gift_certificate_auth_amount_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_auth_amount_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_auth_amount_delta] [bigint] NULL,
[gift_certificate_balance] [bigint] NULL,
[gift_certificate_balance_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_balance_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_balance_delta] [bigint] NULL,
[gift_certificate_bundle_id] [uniqueidentifier] NULL,
[gift_certificate_bundle_item_id] [uniqueidentifier] NULL,
[gift_certificate_create_audit_id] [uniqueidentifier] NULL,
[gift_certificate_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_expiry] [datetime] NULL,
[gift_certificate_id] [uniqueidentifier] NOT NULL,
[gift_certificate_message] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[gift_certificate_redemption_number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_order_id] [uniqueidentifier] NULL,
[gift_certificate_parent_id] [uniqueidentifier] NULL,
[gift_certificate_original_id] [uniqueidentifier] NOT NULL,
[gift_certificate_recipient] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_update_delivery_method_id] [uniqueidentifier] NULL,
[gift_certificate_used_payment_id] [uniqueidentifier] NULL,
[gift_certificate_version] [int] NOT NULL,
[gift_certificate_print_count] [int] NULL,
[gift_certificate_data1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_data2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_data3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_stored_value_id] [uniqueidentifier] NULL,
[gift_certificate_type] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_promo_code_id] [uniqueidentifier] NULL,
[gift_certificate_transaction_state] [int] NOT NULL,
[gift_certificate_agent_id] [uniqueidentifier] NULL,
[gift_certificate_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gift_certificate_access_code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
