CREATE TABLE [bkp].[AV_ts_payment_so]
(
[audit_datetime] [datetime] NULL,
[paymentso_authorization_code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_bank_terminal_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_batch_number] [bigint] NULL,
[paymentso_cardholder_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_customer_language] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_data_block] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_debit_account_type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_expiration_date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_external_reference_number] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_host_date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_host_time] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_id] [uniqueidentifier] NOT NULL,
[paymentso_issue_number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_merchant_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_order_id] [uniqueidentifier] NULL,
[paymentso_parent_id] [uniqueidentifier] NULL,
[paymentso_payment_function] [int] NULL,
[paymentso_payment_id] [uniqueidentifier] NULL,
[paymentso_payment_transaction_type] [int] NULL,
[paymentso_payment_type] [int] NOT NULL,
[paymentso_paymentmethod_id] [uniqueidentifier] NULL,
[paymentso_process_time] [bigint] NULL,
[paymentso_processor] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_receipt_msg] [nvarchar] (1500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_reference_number] [int] NULL,
[paymentso_return_status] [int] NULL,
[paymentso_screen_msg] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_sequence_number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_start_date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_swipe_indicator] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_terminal_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_trans_amount_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_transaction_amount] [bigint] NULL,
[paymentso_transaction_status] [int] NULL,
[paymentso_pa_auth_id] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_pa_auth_status] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_pa_eci] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_gift_certificate_id] [uniqueidentifier] NULL,
[paymentso_redemption_code] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_pa_enabled] [int] NULL,
[paymentso_masked_account_number] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_token] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_account_number_hash] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_options] [int] NULL,
[paymentso_data1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_data2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_data3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_merchant_receipt] [nvarchar] (1500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_signature_status] [int] NULL,
[paymentso_client_address] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_server_address] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_role_id] [uniqueidentifier] NULL,
[paymentso_user_id] [uniqueidentifier] NULL,
[paymentso_user_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_session_id] [uniqueidentifier] NULL,
[paymentso_transaction_date] [datetime] NULL,
[paymentso_correlation_id] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_wallet_indicator] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_card_brand] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_application_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentso_application_name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
