CREATE TABLE [bkp].[AV_ts_bundle]
(
[audit_datetime] [datetime] NULL,
[bundle_record_state] [int] NOT NULL,
[bundle_audit_id] [uniqueidentifier] NOT NULL,
[bundle_create_audit_id] [uniqueidentifier] NULL,
[bundle_description] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_id] [uniqueidentifier] NOT NULL,
[bundle_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[bundle_options] [int] NULL,
[bundle_rank] [int] NULL,
[bundle_type] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_group_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_data1] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_data2] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_data3] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_data4] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_data5] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_data6] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_data7] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_data8] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_additional_info] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_logo1] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_logo2] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_version] [int] NULL,
[bundle_short_description] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_detailed_description] [uniqueidentifier] NULL,
[bundle_addon_article] [uniqueidentifier] NULL,
[bundle_sales_type] [int] NULL,
[bundle_upsell_article] [uniqueidentifier] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
