CREATE TABLE [ods].[AV_ts_user_role]
(
[userrole_record_state] [int] NOT NULL,
[userrole_audit_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_create_audit_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_data1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_data2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_data3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_data4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_data5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_data6] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_data7] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_data8] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_default_delivery_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_default_pricetype_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_default_payment_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_description] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_email_from_address] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_email_template] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_hold_value] [bigint] NULL,
[userrole_card_failure_limit] [int] NULL,
[userrole_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_invoice_template] [uniqueidentifier] NULL,
[userrole_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[userrole_offer_time_out] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_payment_type] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_status] [int] NULL,
[userrole_options] [int] NULL,
[userrole_version] [int] NOT NULL,
[userrole_group] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_reservation_timeout] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_reservation_valid_until] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_default_gift_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_cancel_tickets_template] [uniqueidentifier] NULL,
[userrole_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_ship_to_template] [uniqueidentifier] NULL,
[userrole_username_indicator] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_default_dashboard_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_desktop_article_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userrole_max_seats_per_row] [int] NULL
)
GO
