CREATE TABLE [ods].[AV_ts_order_bundle]
(
[orderbundle_record_state] [int] NOT NULL,
[orderbundle_net] [bigint] NULL,
[orderbundle_net_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_net_delta] [bigint] NULL,
[orderbundle_net_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_price] [bigint] NULL,
[orderbundle_price_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_incl_charge2_delta] [bigint] NULL,
[orderbundle_incl_charge2_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_add_charge2_delta] [bigint] NULL,
[orderbundle_add_charge2_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_add_charge2] [bigint] NULL,
[orderbundle_add_charge2_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_incl_charge2] [bigint] NULL,
[orderbundle_incl_charge2_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_amount] [bigint] NULL,
[orderbundle_amount_delta] [bigint] NULL,
[orderbundle_amount_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_amount_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_audit_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_bundle_version_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_create_audit_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_customerpass_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_assigned_customerpass_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_customer_offer_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_customer_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_description] [nvarchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_ticketnumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_order_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_version] [int] NOT NULL,
[orderbundle_print_count] [int] NULL,
[orderbundle_data1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_data2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_data3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_incl_charge1] [bigint] NULL,
[orderbundle_incl_charge1_delta] [bigint] NULL,
[orderbundle_incl_charge1_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_incl_charge1_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_add_charge1] [bigint] NULL,
[orderbundle_add_charge1_delta] [bigint] NULL,
[orderbundle_add_charge1_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_add_charge1_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_incl_charge3] [bigint] NULL,
[orderbundle_incl_charge3_delta] [bigint] NULL,
[orderbundle_incl_charge3_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_incl_charge3_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_add_charge3] [bigint] NULL,
[orderbundle_add_charge3_delta] [bigint] NULL,
[orderbundle_add_charge3_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_add_charge3_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_incl_charge4] [bigint] NULL,
[orderbundle_incl_charge4_delta] [bigint] NULL,
[orderbundle_incl_charge4_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_incl_charge4_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_add_charge4] [bigint] NULL,
[orderbundle_add_charge4_delta] [bigint] NULL,
[orderbundle_add_charge4_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_add_charge4_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_incl_charge5] [bigint] NULL,
[orderbundle_incl_charge5_delta] [bigint] NULL,
[orderbundle_incl_charge5_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_incl_charge5_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_add_charge5] [bigint] NULL,
[orderbundle_add_charge5_delta] [bigint] NULL,
[orderbundle_add_charge5_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_add_charge5_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_total] [bigint] NULL,
[orderbundle_total_delta] [bigint] NULL,
[orderbundle_total_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_total_currency_delta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbundle_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
