CREATE TABLE [ods].[AV_ts_admission]
(
[admission_record_state] [int] NOT NULL,
[admission_audit_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_create_audit_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_fill_template_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_fill_value_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_hold_template_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_hold_value_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_performance_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_price_template_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_price_value_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_seat_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_ticket_number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_ticket_barcode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_version] [int] NOT NULL,
[admission_acquisition_cost_amount] [bigint] NULL,
[admission_acquisition_cost_currency] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_acquisition_date] [datetime] NULL,
[admission_inventory_status] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_supplier] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_datetime_1] [datetime] NULL,
[admission_datetime_2] [datetime] NULL,
[admission_currency_amount_1] [bigint] NULL,
[admission_currency_type_1] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_currency_amount_2] [bigint] NULL,
[admission_currency_type_2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_data_1] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_data_2] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_data_3] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_data_4] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_data_5] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_data_6] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_data_7] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_data_8] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_data_9] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_reference_number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_message] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_image] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[admission_association] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_CreatedDate] [datetime] NULL
)
GO
