IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBCLOUD\KSniffin')
CREATE LOGIN [SSBCLOUD\KSniffin] FROM WINDOWS
GO
CREATE USER [SSBCLOUD\KSniffin] FOR LOGIN [SSBCLOUD\KSniffin] WITH DEFAULT_SCHEMA=[SSBCLOUD\KSniffin]
GO
REVOKE CONNECT TO [SSBCLOUD\KSniffin]
